###
POST http://localhost:8000/entry
Content-Type: application/json

{
 "text": "My dog died today. I feel heartbroken and lost.",
  "entry_date": "2025-08-31"
}
###

###
POST http://localhost:8000/weekly_summary
Content-Type: application/json

{
"date": "2025-08-31"
}